plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

def ciVersionCode = Integer.parseInt(System.getenv("VERSION_CODE") ?: "1")
def ciVersionName = System.getenv("VERSION_NAME") ?: "1.0.0"
def keystoreFile = System.getenv("KEYSTORE_FILE")

android {
    namespace 'dev.pantherale0.mc40'
    compileSdk 33
    defaultConfig {
        applicationId "dev.pantherale0.mc40"
        minSdk 22
        targetSdk 22
        versionCode ciVersionCode
        versionName ciVersionName
    }
    if (keystoreFile) {
        signingConfigs {
            release {
                storeFile file(keystoreFile)
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
                v1SigningEnabled true
                v2SigningEnabled true
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (keystoreFile) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
    }
    lint {
        checkReleaseBuilds false
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}
